import { isMagicalAbility, type AbilityKey } from "./abilities.js";
import type { CombatActionDef } from "./actions.js";
import type { ItemSlot } from "./items.js";

export interface StartingEquipmentOption {
  id: string;
  /** Short label shown at character creation, e.g. "Longsword & Chain Shirt". */
  label: string;
  equipment: Partial<Record<ItemSlot, string>>;
}

/**
 * One of a class's two named Basic Attack variants (melee/ranged), per the
 * Class Style Sheet's own explicit per-slot name/ability/modifier (e.g.
 * Warrior's "Wild Swing (20% of attack power)"). `ability` is ignored in
 * favor of `basicAttackAbilityMode` for a class that has one (Soldier,
 * Rogue) -- see character.ts's `generateBasicAttacks`.
 *
 * `percentOfAbility` is stored as **double** the sheet's own stated
 * percentage (e.g. Wild Swing's sheet-stated "20% of attack power" is
 * stored as `0.4`, not `0.2`). Attack Power/Spell Power (see the Character
 * Stats Style Sheet) are simply `ability score × 2`, and combat.ts's damage
 * formula multiplies the RAW ability score directly rather than computing
 * Attack/Spell Power first -- doubling the stored coefficient here produces
 * numerically identical results to "X% of Attack/Spell Power" without any
 * engine-side formula change. Keep player-facing `description` text quoting
 * the sheet's own (undoubled) percentage against "Attack Power"/"Spell
 * Power", not this doubled internal value.
 */
export interface BasicAttackVariant {
  name: string;
  ability: AbilityKey;
  percentOfAbility: number;
}

/** A class's own passive ability, shown on the Character screen's Traits panel alongside race traits. */
export interface ClassPassive {
  name: string;
  description: string;
  /** The character level this passive requires (default 1) -- filtered at display time only (see CharacterScreen.tsx); the test covering every class's passive list reads `cls.passives` directly, unfiltered. */
  unlockLevel?: number;
}

export interface CharacterClass {
  id: string;
  name: string;
  description: string;
  primaryAbility: AbilityKey;
  savingThrowProficiencies: AbilityKey[];
  /**
   * Per the Class Style Sheet: this class's own attributes grow by this much
   * on every even level (2, 4, 6, 8, ...) -- see character.ts's
   * `computeAbilityScores`. Replaces the old one-time flat "class bonus"
   * model.
   */
  evenLevelAbilityGrowth: Partial<Record<AbilityKey, number>>;
  /** This class's free, resource-building Basic Attack, one named variant per weapon slot -- the actual action(s) are generated per equipped weapon slot in character.ts's `generateBasicAttacks`, not listed here. */
  basicAttackMelee: BasicAttackVariant;
  basicAttackRanged: BasicAttackVariant;
  /** Soldier only: both Basic Attack variants scale off whichever of STR/DEX is higher, instead of their own listed `ability`. */
  basicAttackAbilityMode?: "highestOfStrDex";
  /**
   * The class's 2 leveled active abilities (Basic Attack and Defend/Flee/End
   * Turn are added separately — see character.ts). Each is filtered by its
   * own `unlockLevel` against `character.level` at action-list assembly
   * time; see actions.ts's `unlockLevel` doc for why this mostly gates
   * everything past a level-1 kit until a leveling system exists.
   */
  actions: CombatActionDef[];
  /** This class's own Class Style Sheet passive(s), for the Character screen's Traits panel. Empty for Rogue, whose passive the sheet itself still just calls "Placeholder". */
  passives: ClassPassive[];
  /** Soldier's "Experience with a blade" passive (+5% parry chance) — modeled as flat Armor Rating, since this engine has no separate parry/riposte roll to hang it on (see README). */
  passiveArmorRating?: number;
  /** Ranger's Sharpshooter passive: flat hit/crit bonus while their ranged weapon is the one swinging. */
  rangedAttackHitBonus?: number;
  rangedAttackCritBonus?: number;
  /**
   * SRD-style "choose (a) or (b)" starting gear, respecting the class's weapon/armor
   * restrictions.
   */
  startingEquipmentOptions: StartingEquipmentOption[];
  /** Extra item ids owned but not equipped at creation (e.g. a spare accessory to try). */
  startingInventory: string[];
}

/**
 * The seven playable classes from the Class Style Sheet (Google Drive,
 * "Class Information/Age of Broken Wings - Class Style Sheet.docx"): every
 * resource pool, resource cost, AP cost, and ability description below is
 * transcribed directly from it. Cooldowns (there are none — the sheet's own
 * resource/AP costs are the limiting factor), damage types where unstated,
 * and each ability's `schoolId` are homebrew, sized to feel right against
 * the existing AP economy and Vitality-scaled HP pools — same precedent as
 * this file's own numbers before this pass.
 *
 * A few mechanics don't have a real equivalent in this engine and are
 * deliberately reinterpreted rather than fabricated wholesale — see
 * `passiveArmorRating`/`rangedAttackHitBonus`'s own comments above, and
 * README's "Class Style Sheet reforge" section for the full list
 * (parry-as-evasion, armor-as-evasion, the flat+percent heal/damage
 * formula, and Rogue's still-"Placeholder" passive, left unimplemented
 * because the sheet itself hasn't decided it yet).
 *
 * A later revision of the sheet reworded every ability's damage/healing
 * scaling to be explicit about Attack Power vs. Spell Power (the Character
 * Stats Style Sheet's two headline offense stats, each `ability score × 2`)
 * rather than a raw ability score -- see `BasicAttackVariant`'s own doc
 * comment for how `percentOfAbility` encodes that without an engine-side
 * formula change. Soldier's and Rogue's "Attack Power = whichever of
 * STR/DEX is higher" both use `basicAttackAbilityMode`. Enrage and Arcane
 * Barrier's buffs stayed a direct Evasion bonus (not real Armor Rating)
 * even though their sheet text now says "armor" -- confirmed with the user
 * this was wording, not a mechanic change.
 */
export const CLASSES: Record<string, CharacterClass> = {
  warrior: {
    id: "warrior",
    name: "Warrior",
    description: "Steel and stubbornness. Warriors build Fury by dealing and taking blows, then spend it on crushing strikes.",
    primaryAbility: "str",
    savingThrowProficiencies: ["str", "vit"],
    evenLevelAbilityGrowth: { str: 2, vit: 2, dex: 1 },
    basicAttackMelee: { name: "Wild Swing", ability: "str", percentOfAbility: 0.4 },
    basicAttackRanged: { name: "Wild Shot", ability: "dex", percentOfAbility: 0.3 },
    /**
     * The Warrior's full kit is online by level 10 (6 actives across levels
     * 1-10, using odd levels too -- not every class's own unlocks need to
     * line up with even-level stat growth); from 11-30 no new abilities
     * arrive, only new ranks of these same six, one rank-up landing almost
     * every level all the way to 30 (see README's dated entry for the full
     * per-ability table this was planned from). Each rank is its own entry
     * sharing a `familyId`; `applyEquipmentEffects` keeps only the highest
     * one a character's level qualifies for. Furious Strike and Warlord's
     * Reckoning both carry `requiresStatusDefId: "fortified"` -- Enrage's
     * own buff -- finally paying off Enrage's long-dangling "you can use
     * abilities that require Enraged" line from the original lvl 1-4 kit.
     */
    actions: [
      {
        id: "enrage",
        name: "Enrage",
        description:
          "A furious battle-cry: for 5 turns, evasion increases by 50% of your Vitality score and you can use abilities that require Enraged. Costs Fury.",
        kind: "buff",
        target: "self",
        ability: "vit",
        resourceCost: 20,
        apCost: 2,
        schoolId: "martial",
        applyStatus: { defId: "fortified", turns: 5, power: 0.5 },
        familyId: "enrage",
        rank: 1,
      },
      {
        id: "enrage-r2",
        name: "Enrage (Rank 2)",
        description:
          "A furious battle-cry: for 5 turns, evasion increases by 65% of your Vitality score and you can use abilities that require Enraged. Costs Fury.",
        kind: "buff",
        target: "self",
        ability: "vit",
        resourceCost: 20,
        apCost: 2,
        schoolId: "martial",
        applyStatus: { defId: "fortified", turns: 5, power: 0.65 },
        familyId: "enrage",
        rank: 2,
        unlockLevel: 11,
      },
      {
        id: "enrage-r3",
        name: "Enrage (Rank 3)",
        description:
          "A furious battle-cry: for 5 turns, evasion increases by 80% of your Vitality score and you can use abilities that require Enraged. Costs Fury.",
        kind: "buff",
        target: "self",
        ability: "vit",
        resourceCost: 20,
        apCost: 2,
        schoolId: "martial",
        applyStatus: { defId: "fortified", turns: 5, power: 0.8 },
        familyId: "enrage",
        rank: 3,
        unlockLevel: 18,
      },
      {
        id: "enrage-r4",
        name: "Enrage (Rank 4)",
        description:
          "A furious battle-cry: for 5 turns, evasion increases by 100% of your Vitality score and you can use abilities that require Enraged. Costs Fury.",
        kind: "buff",
        target: "self",
        ability: "vit",
        resourceCost: 20,
        apCost: 2,
        schoolId: "martial",
        applyStatus: { defId: "fortified", turns: 5, power: 1.0 },
        familyId: "enrage",
        rank: 4,
        unlockLevel: 25,
      },
      {
        id: "cleave",
        name: "Cleave",
        description: "A wide arcing attack that strikes every enemy in the target's row. Weapon damage + 20% of your Attack Power. Costs Fury.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 0.4,
        resourceCost: 50,
        apCost: 2,
        schoolId: "martial",
        unlockLevel: 2,
        familyId: "cleave",
        rank: 1,
      },
      {
        id: "cleave-r2",
        name: "Cleave (Rank 2)",
        description: "A wide arcing attack that strikes every enemy in the target's row. Weapon damage + 26% of your Attack Power. Costs Fury.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 0.52,
        resourceCost: 55,
        apCost: 2,
        schoolId: "martial",
        unlockLevel: 13,
        familyId: "cleave",
        rank: 2,
      },
      {
        id: "cleave-r3",
        name: "Cleave (Rank 3)",
        description: "A wide arcing attack that strikes every enemy in the target's row. Weapon damage + 33% of your Attack Power. Costs Fury.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 0.66,
        resourceCost: 60,
        apCost: 2,
        schoolId: "martial",
        unlockLevel: 20,
        familyId: "cleave",
        rank: 3,
      },
      {
        id: "cleave-r4",
        name: "Cleave (Rank 4)",
        description: "A wide arcing attack that strikes every enemy in the target's row. Weapon damage + 40% of your Attack Power. Costs Fury.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 0.8,
        resourceCost: 65,
        apCost: 2,
        schoolId: "martial",
        unlockLevel: 27,
        familyId: "cleave",
        rank: 4,
      },
      {
        id: "serrated-blade",
        name: "Serrated Blade",
        description: "A vicious slashing attack that wounds the target, causing them to bleed for 3 turns. Weapon damage. Costs Fury.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        resourceCost: 30,
        apCost: 2,
        schoolId: "martial",
        applyStatus: { defId: "bleeding", turns: 3, weaponPercent: 0.1 },
        unlockLevel: 4,
        familyId: "serrated-blade",
        rank: 1,
      },
      {
        id: "serrated-blade-r2",
        name: "Serrated Blade (Rank 2)",
        description: "A vicious slashing attack that wounds the target, causing them to bleed for 3 turns for 13% Attack Power. Weapon damage. Costs Fury.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        resourceCost: 33,
        apCost: 2,
        schoolId: "martial",
        applyStatus: { defId: "bleeding", turns: 3, weaponPercent: 0.13 },
        unlockLevel: 12,
        familyId: "serrated-blade",
        rank: 2,
      },
      {
        id: "serrated-blade-r3",
        name: "Serrated Blade (Rank 3)",
        description: "A vicious slashing attack that wounds the target, causing them to bleed for 3 turns for 16% Attack Power. Weapon damage. Costs Fury.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        resourceCost: 36,
        apCost: 2,
        schoolId: "martial",
        applyStatus: { defId: "bleeding", turns: 3, weaponPercent: 0.16 },
        unlockLevel: 19,
        familyId: "serrated-blade",
        rank: 3,
      },
      {
        id: "serrated-blade-r4",
        name: "Serrated Blade (Rank 4)",
        description: "A vicious slashing attack that wounds the target, causing them to bleed for 3 turns for 20% Attack Power. Weapon damage. Costs Fury.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        resourceCost: 40,
        apCost: 2,
        schoolId: "martial",
        applyStatus: { defId: "bleeding", turns: 3, weaponPercent: 0.2 },
        unlockLevel: 26,
        familyId: "serrated-blade",
        rank: 4,
      },
      {
        id: "furious-strike",
        name: "Furious Strike",
        description:
          "A single devastating blow fueled by rage. Weapon damage + 40% of your Attack Power. Requires Enraged. Costs Fury.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 0.8,
        resourceCost: 40,
        apCost: 2,
        schoolId: "martial",
        requiresStatusDefId: "fortified",
        unlockLevel: 6,
        familyId: "furious-strike",
        rank: 1,
      },
      {
        id: "furious-strike-r2",
        name: "Furious Strike (Rank 2)",
        description:
          "A single devastating blow fueled by rage. Weapon damage + 50% of your Attack Power. Requires Enraged. Costs Fury.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 1.0,
        resourceCost: 45,
        apCost: 2,
        schoolId: "martial",
        requiresStatusDefId: "fortified",
        unlockLevel: 21,
        familyId: "furious-strike",
        rank: 2,
      },
      {
        id: "furious-strike-r3",
        name: "Furious Strike (Rank 3)",
        description:
          "A single devastating blow fueled by rage. Weapon damage + 60% of your Attack Power. Requires Enraged. Costs Fury.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 1.2,
        resourceCost: 50,
        apCost: 2,
        schoolId: "martial",
        requiresStatusDefId: "fortified",
        unlockLevel: 28,
        familyId: "furious-strike",
        rank: 3,
      },
      {
        id: "bulwark-stance",
        name: "Bulwark Stance",
        description:
          "Plants firm and braces for the next blow: for 1 turn, evasion increases by 100% of your Vitality score. Costs Fury.",
        kind: "buff",
        target: "self",
        ability: "vit",
        resourceCost: 25,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "braced", turns: 1, power: 1.0 },
        unlockLevel: 8,
        familyId: "bulwark-stance",
        rank: 1,
      },
      {
        id: "bulwark-stance-r2",
        name: "Bulwark Stance (Rank 2)",
        description:
          "Plants firm and braces for the next blow: for 1 turn, evasion increases by 120% of your Vitality score. Costs Fury.",
        kind: "buff",
        target: "self",
        ability: "vit",
        resourceCost: 25,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "braced", turns: 1, power: 1.2 },
        unlockLevel: 15,
        familyId: "bulwark-stance",
        rank: 2,
      },
      {
        id: "bulwark-stance-r3",
        name: "Bulwark Stance (Rank 3)",
        description:
          "Plants firm and braces for the next blows: for 2 turns, evasion increases by 140% of your Vitality score. Costs Fury.",
        kind: "buff",
        target: "self",
        ability: "vit",
        resourceCost: 25,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "braced", turns: 2, power: 1.4 },
        unlockLevel: 22,
        familyId: "bulwark-stance",
        rank: 3,
      },
      {
        id: "warlords-reckoning",
        name: "Warlord's Reckoning",
        description:
          "A devastating cleave fueled by rage, striking every enemy in the target's row. Weapon damage + 50% of your Attack Power. Requires Enraged. Costs Fury.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 1.0,
        resourceCost: 60,
        apCost: 3,
        schoolId: "martial",
        requiresStatusDefId: "fortified",
        unlockLevel: 10,
        familyId: "warlords-reckoning",
        rank: 1,
      },
      {
        id: "warlords-reckoning-r2",
        name: "Warlord's Reckoning (Rank 2)",
        description:
          "A devastating cleave fueled by rage, striking every enemy in the target's row. Weapon damage + 60% of your Attack Power. Requires Enraged. Costs Fury.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 1.2,
        resourceCost: 65,
        apCost: 3,
        schoolId: "martial",
        requiresStatusDefId: "fortified",
        unlockLevel: 17,
        familyId: "warlords-reckoning",
        rank: 2,
      },
      {
        id: "warlords-reckoning-r3",
        name: "Warlord's Reckoning (Rank 3)",
        description:
          "A devastating cleave fueled by rage, striking every enemy in the target's row. Weapon damage + 70% of your Attack Power. Requires Enraged. Costs Fury.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 1.4,
        resourceCost: 70,
        apCost: 3,
        schoolId: "martial",
        requiresStatusDefId: "fortified",
        unlockLevel: 24,
        familyId: "warlords-reckoning",
        rank: 3,
      },
      {
        id: "warlords-reckoning-r4",
        name: "Warlord's Reckoning (Rank 4)",
        description:
          "A devastating cleave fueled by rage, striking every enemy in the target's row. Weapon damage + 85% of your Attack Power. Requires Enraged. Costs Fury.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 1.7,
        resourceCost: 75,
        apCost: 3,
        schoolId: "martial",
        requiresStatusDefId: "fortified",
        unlockLevel: 30,
        familyId: "warlords-reckoning",
        rank: 4,
      },
    ],
    // Furious and Reckless's actual numbers are ranked by level (see combat.ts's
    // `furiousPercent`/`recklessMultiplier`) but described generically here rather than
    // listing one specific rank's figure that would go stale the moment a character ranks
    // up -- passives aren't modeled with the same familyId/rank mechanism active abilities
    // use above, since nothing else needs to resolve "the current rank of a passive" structurally.
    passives: [
      {
        name: "Furious",
        description:
          "Generates Fury when struck by an enemy, equal to a percentage of the damage taken -- 25% to start, growing as you gain experience.",
      },
      {
        name: "Reckless",
        description:
          "While below half HP, Fury gained from Furious and from landing your Basic Attack is increased -- more so, and at an even higher HP threshold, as you gain experience.",
        unlockLevel: 5,
      },
    ],
    startingEquipmentOptions: [
      { id: "sword-and-mail", label: "Longsword & Chain Shirt", equipment: { meleeWeapon: "ironLongsword", armor: "chainShirt" } },
      { id: "sword-and-leather", label: "Longsword & Studded Leather", equipment: { meleeWeapon: "ironLongsword", armor: "studdedLeather" } },
    ],
    startingInventory: ["luckyCharm"],
  },
  soldier: {
    id: "soldier",
    name: "Soldier",
    description: "A disciplined blade-and-shield fighter, trading burst damage for tempo: knock foes down and punish their openings.",
    primaryAbility: "str",
    savingThrowProficiencies: ["str", "dex"],
    evenLevelAbilityGrowth: { str: 2, dex: 2, vit: 1 },
    basicAttackMelee: { name: "Practiced Strike", ability: "str", percentOfAbility: 0.3 },
    basicAttackRanged: { name: "Steady Shot", ability: "dex", percentOfAbility: 0.3 },
    basicAttackAbilityMode: "highestOfStrDex",
    /**
     * Same ranked-ability shape as the Warrior (see that class's own doc
     * comment): the Soldier's full 5-active kit is online by level 10, then
     * ranks up through 30. Expertise is a much tighter resource than Fury
     * (a fixed 10-point pool, +1 per landed Basic Attack/+2 on crit) so this
     * kit leans on fewer, cheaper, higher-impact buttons rather than
     * Warrior-style big spends -- Riposte Stance -> Counter-Strike is the
     * Soldier's own stance/gated-finisher pair (mirroring Enrage -> Furious
     * Strike), using a new "parrying" buff id (status.ts) so it doesn't
     * double as a Warrior requirement.
     */
    actions: [
      {
        id: "defensive-flourish",
        name: "Defensive Flourish",
        description:
          "A slashing attack, then a defensive stance: gain 2 stacks of Readied, each reducing an attacker's chance to hit you by 50% until spent. Weapon damage. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        resourceCost: 3,
        apCost: 2,
        schoolId: "martial",
        applySelfStatus: { defId: "readied", turns: 99, stacks: 2 },
        unlockLevel: 2,
        familyId: "defensive-flourish",
        rank: 1,
      },
      {
        id: "defensive-flourish-r2",
        name: "Defensive Flourish (Rank 2)",
        description:
          "A slashing attack, then a defensive stance: gain 2 stacks of Readied, each reducing an attacker's chance to hit you by 50% until spent. Weapon damage + 10% of your Attack Power. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 0.2,
        resourceCost: 4,
        apCost: 2,
        schoolId: "martial",
        applySelfStatus: { defId: "readied", turns: 99, stacks: 2 },
        unlockLevel: 11,
        familyId: "defensive-flourish",
        rank: 2,
      },
      {
        id: "defensive-flourish-r3",
        name: "Defensive Flourish (Rank 3)",
        description:
          "A slashing attack, then a defensive stance: gain 3 stacks of Readied, each reducing an attacker's chance to hit you by 50% until spent. Weapon damage + 15% of your Attack Power. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 0.3,
        resourceCost: 5,
        apCost: 2,
        schoolId: "martial",
        applySelfStatus: { defId: "readied", turns: 99, stacks: 3 },
        unlockLevel: 18,
        familyId: "defensive-flourish",
        rank: 3,
      },
      {
        id: "defensive-flourish-r4",
        name: "Defensive Flourish (Rank 4)",
        description:
          "A slashing attack, then a defensive stance: gain 3 stacks of Readied, each reducing an attacker's chance to hit you by 50% until spent. Weapon damage + 20% of your Attack Power. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 0.4,
        resourceCost: 6,
        apCost: 2,
        schoolId: "martial",
        applySelfStatus: { defId: "readied", turns: 99, stacks: 3 },
        unlockLevel: 25,
        familyId: "defensive-flourish",
        rank: 4,
      },
      {
        id: "topple",
        name: "Topple",
        description: "Hooks the target's leg for weapon damage + 20% of your Attack Power, knocking them down for 1 turn. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "bludgeoning",
        percentOfAbility: 0.4,
        resourceCost: 5,
        apCost: 3,
        schoolId: "martial",
        applyStatus: { defId: "knockedDown", turns: 1 },
        unlockLevel: 4,
        familyId: "topple",
        rank: 1,
      },
      {
        id: "topple-r2",
        name: "Topple (Rank 2)",
        description: "Hooks the target's leg for weapon damage + 24% of your Attack Power, knocking them down for 1 turn. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "bludgeoning",
        percentOfAbility: 0.48,
        resourceCost: 6,
        apCost: 3,
        schoolId: "martial",
        applyStatus: { defId: "knockedDown", turns: 1 },
        unlockLevel: 12,
        familyId: "topple",
        rank: 2,
      },
      {
        id: "topple-r3",
        name: "Topple (Rank 3)",
        description: "Hooks the target's leg for weapon damage + 28% of your Attack Power, knocking them down for 1 turn. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "bludgeoning",
        percentOfAbility: 0.56,
        resourceCost: 7,
        apCost: 3,
        schoolId: "martial",
        applyStatus: { defId: "knockedDown", turns: 1 },
        unlockLevel: 19,
        familyId: "topple",
        rank: 3,
      },
      {
        id: "topple-r4",
        name: "Topple (Rank 4)",
        description: "Hooks the target's leg for weapon damage + 32% of your Attack Power, knocking them down for 1 turn. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "bludgeoning",
        percentOfAbility: 0.64,
        resourceCost: 8,
        apCost: 3,
        schoolId: "martial",
        applyStatus: { defId: "knockedDown", turns: 1 },
        unlockLevel: 26,
        familyId: "topple",
        rank: 4,
      },
      {
        id: "riposte-stance",
        name: "Riposte Stance",
        description: "Settles into a parrying stance: for 3 turns, evasion increases by 60% of your Vitality score. Costs Expertise.",
        kind: "buff",
        target: "self",
        ability: "vit",
        resourceCost: 4,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "parrying", turns: 3, power: 0.6 },
        unlockLevel: 6,
        familyId: "riposte-stance",
        rank: 1,
      },
      {
        id: "riposte-stance-r2",
        name: "Riposte Stance (Rank 2)",
        description: "Settles into a parrying stance: for 3 turns, evasion increases by 75% of your Vitality score. Costs Expertise.",
        kind: "buff",
        target: "self",
        ability: "vit",
        resourceCost: 4,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "parrying", turns: 3, power: 0.75 },
        unlockLevel: 15,
        familyId: "riposte-stance",
        rank: 2,
      },
      {
        id: "riposte-stance-r3",
        name: "Riposte Stance (Rank 3)",
        description: "Settles into a parrying stance: for 4 turns, evasion increases by 90% of your Vitality score. Costs Expertise.",
        kind: "buff",
        target: "self",
        ability: "vit",
        resourceCost: 5,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "parrying", turns: 4, power: 0.9 },
        unlockLevel: 22,
        familyId: "riposte-stance",
        rank: 3,
      },
      {
        id: "counter-strike",
        name: "Counter-Strike",
        description:
          "A precise, punishing riposte. Weapon damage + 40% of your Attack Power. Requires Parrying. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 0.8,
        resourceCost: 5,
        apCost: 2,
        schoolId: "martial",
        requiresStatusDefId: "parrying",
        unlockLevel: 8,
        familyId: "counter-strike",
        rank: 1,
      },
      {
        id: "counter-strike-r2",
        name: "Counter-Strike (Rank 2)",
        description:
          "A precise, punishing riposte. Weapon damage + 50% of your Attack Power. Requires Parrying. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 1.0,
        resourceCost: 6,
        apCost: 2,
        schoolId: "martial",
        requiresStatusDefId: "parrying",
        unlockLevel: 23,
        familyId: "counter-strike",
        rank: 2,
      },
      {
        id: "counter-strike-r3",
        name: "Counter-Strike (Rank 3)",
        description:
          "A precise, punishing riposte. Weapon damage + 60% of your Attack Power. Requires Parrying. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "slashing",
        percentOfAbility: 1.2,
        resourceCost: 7,
        apCost: 2,
        schoolId: "martial",
        requiresStatusDefId: "parrying",
        unlockLevel: 29,
        familyId: "counter-strike",
        rank: 3,
      },
      {
        id: "shield-sweep",
        name: "Shield Sweep",
        description:
          "A sweeping shield bash across the target's row. Weapon damage + 30% of your Attack Power, with a 50% chance to knock down each enemy struck for 1 turn. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "bludgeoning",
        percentOfAbility: 0.6,
        resourceCost: 8,
        apCost: 3,
        schoolId: "martial",
        applyStatus: { defId: "knockedDown", turns: 1, chance: 50 },
        unlockLevel: 10,
        familyId: "shield-sweep",
        rank: 1,
      },
      {
        id: "shield-sweep-r2",
        name: "Shield Sweep (Rank 2)",
        description:
          "A sweeping shield bash across the target's row. Weapon damage + 35% of your Attack Power, with a 55% chance to knock down each enemy struck for 1 turn. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "bludgeoning",
        percentOfAbility: 0.7,
        resourceCost: 8,
        apCost: 3,
        schoolId: "martial",
        applyStatus: { defId: "knockedDown", turns: 1, chance: 55 },
        unlockLevel: 17,
        familyId: "shield-sweep",
        rank: 2,
      },
      {
        id: "shield-sweep-r3",
        name: "Shield Sweep (Rank 3)",
        description:
          "A sweeping shield bash across the target's row. Weapon damage + 40% of your Attack Power, with a 60% chance to knock down each enemy struck for 1 turn. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "bludgeoning",
        percentOfAbility: 0.8,
        resourceCost: 9,
        apCost: 3,
        schoolId: "martial",
        applyStatus: { defId: "knockedDown", turns: 1, chance: 60 },
        unlockLevel: 24,
        familyId: "shield-sweep",
        rank: 3,
      },
      {
        id: "shield-sweep-r4",
        name: "Shield Sweep (Rank 4)",
        description:
          "A sweeping shield bash across the target's row. Weapon damage + 45% of your Attack Power, with a 65% chance to knock down each enemy struck for 1 turn. Costs Expertise.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "str",
        weaponDamageSource: "melee",
        damageType: "bludgeoning",
        percentOfAbility: 0.9,
        resourceCost: 9,
        apCost: 3,
        schoolId: "martial",
        applyStatus: { defId: "knockedDown", turns: 1, chance: 65 },
        unlockLevel: 30,
        familyId: "shield-sweep",
        rank: 4,
      },
    ],
    passives: [{ name: "Experience with a Blade", description: "Parry chance increased by 5%." }],
    // "Experience with a blade": +5% parry chance -- see passiveArmorRating's own doc comment.
    passiveArmorRating: 100,
    startingEquipmentOptions: [
      { id: "sword-and-mail", label: "Shortsword & Chain Shirt", equipment: { meleeWeapon: "shortsword", armor: "chainShirt" } },
      { id: "sword-and-leather", label: "Shortsword & Studded Leather", equipment: { meleeWeapon: "shortsword", armor: "studdedLeather" } },
    ],
    startingInventory: ["luckyCharm"],
  },
  cleric: {
    id: "cleric",
    name: "Cleric",
    description: "A vessel of the dawn. Clerics mend wounds and lash out with radiant judgment, husbanding a slim reserve of Prayer.",
    primaryAbility: "wis",
    savingThrowProficiencies: ["wis"],
    evenLevelAbilityGrowth: { wis: 2, str: 1, vit: 1 },
    basicAttackMelee: { name: "Swinging Smite", ability: "str", percentOfAbility: 0.3 },
    basicAttackRanged: { name: "Radiance", ability: "wis", percentOfAbility: 0.3 },
    /**
     * Same ranked-ability shape as the Warrior/Soldier (see those classes'
     * own doc comments): the Cleric's full 5-active kit is online by level
     * 10, then ranks up through 30. Prayer is the tightest resource of any
     * class so far -- a fixed 5-point pool, +1 per landed Basic Attack/+2 on
     * crit -- so every cost here stays in the 1-5 range. Ward and Sanctuary
     * lean on a small, generically useful combat.ts fix: a "heal"-kind
     * action's `applyStatus` now lands on the same target it just healed
     * (mirroring what `resolveAttack` already did for its own target), which
     * is what lets a heal also carry a shield (Ward's "ward") or a HoT
     * (Grace's own "grace" status, status.ts) onto an ally.
     */
    actions: [
      {
        id: "mend",
        name: "Mend",
        description: "Calls upon your deity to restore health: heals an ally for 40 + 10% of your Spell Power. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 40,
        percentOfAbility: 0.2,
        resourceCost: 1,
        apCost: 2,
        schoolId: "radiant",
        unlockLevel: 2,
        familyId: "mend",
        rank: 1,
      },
      {
        id: "mend-r2",
        name: "Mend (Rank 2)",
        description: "Calls upon your deity to restore health: heals an ally for 48 + 12% of your Spell Power. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 48,
        percentOfAbility: 0.24,
        resourceCost: 1,
        apCost: 2,
        schoolId: "radiant",
        unlockLevel: 11,
        familyId: "mend",
        rank: 2,
      },
      {
        id: "mend-r3",
        name: "Mend (Rank 3)",
        description: "Calls upon your deity to restore health: heals an ally for 56 + 14% of your Spell Power. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 56,
        percentOfAbility: 0.28,
        resourceCost: 1,
        apCost: 2,
        schoolId: "radiant",
        unlockLevel: 18,
        familyId: "mend",
        rank: 3,
      },
      {
        id: "mend-r4",
        name: "Mend (Rank 4)",
        description: "Calls upon your deity to restore health: heals an ally for 64 + 16% of your Spell Power. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 64,
        percentOfAbility: 0.32,
        resourceCost: 1,
        apCost: 2,
        schoolId: "radiant",
        unlockLevel: 25,
        familyId: "mend",
        rank: 4,
      },
      {
        id: "radiant-beam",
        name: "Radiant Beam",
        description:
          "Calls down a divine beam, damaging the target and adjacent enemies in their row for 40 + 20% of your Spell Power. Costs Prayer.",
        kind: "attack",
        target: "enemy",
        targetShape: "area",
        ability: "wis",
        damageType: "radiant",
        flatBase: 40,
        percentOfAbility: 0.4,
        resourceCost: 4,
        apCost: 3,
        schoolId: "radiant",
        unlockLevel: 4,
        familyId: "radiant-beam",
        rank: 1,
      },
      {
        id: "radiant-beam-r2",
        name: "Radiant Beam (Rank 2)",
        description:
          "Calls down a divine beam, damaging the target and adjacent enemies in their row for 48 + 24% of your Spell Power. Costs Prayer.",
        kind: "attack",
        target: "enemy",
        targetShape: "area",
        ability: "wis",
        damageType: "radiant",
        flatBase: 48,
        percentOfAbility: 0.48,
        resourceCost: 4,
        apCost: 3,
        schoolId: "radiant",
        unlockLevel: 12,
        familyId: "radiant-beam",
        rank: 2,
      },
      {
        id: "radiant-beam-r3",
        name: "Radiant Beam (Rank 3)",
        description:
          "Calls down a divine beam, damaging the target and adjacent enemies in their row for 56 + 28% of your Spell Power. Costs Prayer.",
        kind: "attack",
        target: "enemy",
        targetShape: "area",
        ability: "wis",
        damageType: "radiant",
        flatBase: 56,
        percentOfAbility: 0.56,
        resourceCost: 5,
        apCost: 3,
        schoolId: "radiant",
        unlockLevel: 19,
        familyId: "radiant-beam",
        rank: 3,
      },
      {
        id: "radiant-beam-r4",
        name: "Radiant Beam (Rank 4)",
        description:
          "Calls down a divine beam, damaging the target and adjacent enemies in their row for 64 + 32% of your Spell Power. Costs Prayer.",
        kind: "attack",
        target: "enemy",
        targetShape: "area",
        ability: "wis",
        damageType: "radiant",
        flatBase: 64,
        percentOfAbility: 0.64,
        resourceCost: 5,
        apCost: 3,
        schoolId: "radiant",
        unlockLevel: 26,
        familyId: "radiant-beam",
        rank: 4,
      },
      {
        id: "ward",
        name: "Ward",
        description: "Wreathes an ally in protective light: for 3 turns, absorbs damage equal to 30% of your Spell Power. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 0,
        resourceCost: 2,
        apCost: 2,
        schoolId: "protection",
        applyStatus: { defId: "ward", turns: 3, power: 0.6 },
        unlockLevel: 6,
        familyId: "ward",
        rank: 1,
      },
      {
        id: "ward-r2",
        name: "Ward (Rank 2)",
        description: "Wreathes an ally in protective light: for 3 turns, absorbs damage equal to 40% of your Spell Power. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 0,
        resourceCost: 2,
        apCost: 2,
        schoolId: "protection",
        applyStatus: { defId: "ward", turns: 3, power: 0.8 },
        unlockLevel: 15,
        familyId: "ward",
        rank: 2,
      },
      {
        id: "ward-r3",
        name: "Ward (Rank 3)",
        description: "Wreathes an ally in protective light: for 4 turns, absorbs damage equal to 50% of your Spell Power. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 0,
        resourceCost: 2,
        apCost: 2,
        schoolId: "protection",
        applyStatus: { defId: "ward", turns: 4, power: 1.0 },
        unlockLevel: 22,
        familyId: "ward",
        rank: 3,
      },
      {
        id: "grace",
        name: "Grace",
        description:
          "A gentle benediction: heals an ally for 10, then another 15% of your Spell Power at the start of each of their turns for 3 turns. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 10,
        resourceCost: 2,
        apCost: 2,
        schoolId: "radiant",
        applyStatus: { defId: "grace", turns: 3, power: 0.3 },
        unlockLevel: 8,
        familyId: "grace",
        rank: 1,
      },
      {
        id: "grace-r2",
        name: "Grace (Rank 2)",
        description:
          "A gentle benediction: heals an ally for 14, then another 18% of your Spell Power at the start of each of their turns for 3 turns. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 14,
        resourceCost: 2,
        apCost: 2,
        schoolId: "radiant",
        applyStatus: { defId: "grace", turns: 3, power: 0.36 },
        unlockLevel: 16,
        familyId: "grace",
        rank: 2,
      },
      {
        id: "grace-r3",
        name: "Grace (Rank 3)",
        description:
          "A gentle benediction: heals an ally for 18, then another 21% of your Spell Power at the start of each of their turns for 4 turns. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 18,
        resourceCost: 3,
        apCost: 2,
        schoolId: "radiant",
        applyStatus: { defId: "grace", turns: 4, power: 0.42 },
        unlockLevel: 23,
        familyId: "grace",
        rank: 3,
      },
      {
        id: "sanctuary",
        name: "Sanctuary",
        description:
          "Calls down the full weight of your deity's favor: heals an ally for 60 + 15% of your Spell Power and shields them for 3 turns, absorbing damage equal to 40% of your Spell Power. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 60,
        percentOfAbility: 0.3,
        resourceCost: 5,
        apCost: 3,
        schoolId: "protection",
        applyStatus: { defId: "ward", turns: 3, power: 0.8 },
        unlockLevel: 10,
        familyId: "sanctuary",
        rank: 1,
      },
      {
        id: "sanctuary-r2",
        name: "Sanctuary (Rank 2)",
        description:
          "Calls down the full weight of your deity's favor: heals an ally for 70 + 18% of your Spell Power and shields them for 3 turns, absorbing damage equal to 47.5% of your Spell Power. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 70,
        percentOfAbility: 0.36,
        resourceCost: 5,
        apCost: 3,
        schoolId: "protection",
        applyStatus: { defId: "ward", turns: 3, power: 0.95 },
        unlockLevel: 17,
        familyId: "sanctuary",
        rank: 2,
      },
      {
        id: "sanctuary-r3",
        name: "Sanctuary (Rank 3)",
        description:
          "Calls down the full weight of your deity's favor: heals an ally for 80 + 21% of your Spell Power and shields them for 4 turns, absorbing damage equal to 55% of your Spell Power. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 80,
        percentOfAbility: 0.42,
        resourceCost: 5,
        apCost: 3,
        schoolId: "protection",
        applyStatus: { defId: "ward", turns: 4, power: 1.1 },
        unlockLevel: 24,
        familyId: "sanctuary",
        rank: 3,
      },
      {
        id: "sanctuary-r4",
        name: "Sanctuary (Rank 4)",
        description:
          "Calls down the full weight of your deity's favor: heals an ally for 90 + 24% of your Spell Power and shields them for 4 turns, absorbing damage equal to 62.5% of your Spell Power. Costs Prayer.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 90,
        percentOfAbility: 0.48,
        resourceCost: 5,
        apCost: 3,
        schoolId: "protection",
        applyStatus: { defId: "ward", turns: 4, power: 1.25 },
        unlockLevel: 30,
        familyId: "sanctuary",
        rank: 4,
      },
    ],
    passives: [
      { name: "Spellcasting", description: "Your spells' damage and healing scale off your Spell Power." },
    ],
    startingEquipmentOptions: [
      {
        id: "mace-and-leather",
        label: "Ashen Mace, Radiance & Studded Leather",
        equipment: { meleeWeapon: "ashenMace", rangedWeapon: "radiance", armor: "studdedLeather" },
      },
      {
        id: "mace-and-mail",
        label: "Ashen Mace, Radiance & Chain Shirt",
        equipment: { meleeWeapon: "ashenMace", rangedWeapon: "radiance", armor: "chainShirt" },
      },
    ],
    startingInventory: ["ringOfWarding"],
  },
  ranger: {
    id: "ranger",
    name: "Ranger",
    description: "A sharpshooting scout, favoring the bow but never without a blade close at hand.",
    primaryAbility: "dex",
    savingThrowProficiencies: ["dex", "wis"],
    evenLevelAbilityGrowth: { dex: 2, wis: 1, vit: 1 },
    basicAttackMelee: { name: "Blade Slash", ability: "str", percentOfAbility: 0.3 },
    basicAttackRanged: { name: "Quick Shot", ability: "dex", percentOfAbility: 0.4 },
    /**
     * Same ranked-ability shape as the Warrior/Soldier/Cleric (see those
     * classes' own doc comments): the Ranger's full 5-active kit is online
     * by level 10, then ranks up through 30. Focus is as tight as Prayer (a
     * fixed 5-point pool, +1 per landed Basic Attack/+2 on crit), so costs
     * stay in the 2-5 range. Barbed Arrow only ranks up its stack count (its
     * per-hit bleed percent is a module-level constant in combat.ts, not
     * data-driven -- same choice Soldier's Readied made, where only the
     * stack count grew across ranks). Evasive Maneuvers -> Kill Shot is the
     * Ranger's own stance/gated-finisher pair (mirroring Enrage -> Furious
     * Strike, Riposte Stance -> Counter-Strike), using a new "evasive" buff
     * id (status.ts). Pinning Shot claims the engine's "rooted" CC status,
     * unused by any class until now.
     */
    actions: [
      {
        id: "barbed-arrow",
        name: "Barbed Arrow",
        description: "Arms your next 2 attacks with barbed arrowheads, causing the target to bleed for 5% of your Attack Power. Costs Focus.",
        kind: "buff",
        target: "self",
        ability: "dex",
        resourceCost: 2,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "barbedPrimed", turns: 99, stacks: 2 },
        unlockLevel: 2,
        familyId: "barbed-arrow",
        rank: 1,
      },
      {
        id: "barbed-arrow-r2",
        name: "Barbed Arrow (Rank 2)",
        description: "Arms your next 3 attacks with barbed arrowheads, causing the target to bleed for 5% of your Attack Power. Costs Focus.",
        kind: "buff",
        target: "self",
        ability: "dex",
        resourceCost: 2,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "barbedPrimed", turns: 99, stacks: 3 },
        unlockLevel: 12,
        familyId: "barbed-arrow",
        rank: 2,
      },
      {
        id: "barbed-arrow-r3",
        name: "Barbed Arrow (Rank 3)",
        description: "Arms your next 4 attacks with barbed arrowheads, causing the target to bleed for 5% of your Attack Power. Costs Focus.",
        kind: "buff",
        target: "self",
        ability: "dex",
        resourceCost: 3,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "barbedPrimed", turns: 99, stacks: 4 },
        unlockLevel: 20,
        familyId: "barbed-arrow",
        rank: 3,
      },
      {
        id: "natures-remedy",
        name: "Nature's Remedy",
        description: "Forages for herbs to mend a wound: heals you for 30 + 20% of your Spell Power. Costs Focus.",
        kind: "heal",
        target: "self",
        ability: "wis",
        flatBase: 30,
        percentOfAbility: 0.4,
        resourceCost: 2,
        apCost: 2,
        schoolId: "martial",
        unlockLevel: 4,
        familyId: "natures-remedy",
        rank: 1,
      },
      {
        id: "natures-remedy-r2",
        name: "Nature's Remedy (Rank 2)",
        description: "Forages for herbs to mend a wound: heals you for 36 + 24% of your Spell Power. Costs Focus.",
        kind: "heal",
        target: "self",
        ability: "wis",
        flatBase: 36,
        percentOfAbility: 0.48,
        resourceCost: 2,
        apCost: 2,
        schoolId: "martial",
        unlockLevel: 11,
        familyId: "natures-remedy",
        rank: 2,
      },
      {
        id: "natures-remedy-r3",
        name: "Nature's Remedy (Rank 3)",
        description: "Forages for herbs to mend a wound: heals you for 42 + 28% of your Spell Power. Costs Focus.",
        kind: "heal",
        target: "self",
        ability: "wis",
        flatBase: 42,
        percentOfAbility: 0.56,
        resourceCost: 3,
        apCost: 2,
        schoolId: "martial",
        unlockLevel: 18,
        familyId: "natures-remedy",
        rank: 3,
      },
      {
        id: "natures-remedy-r4",
        name: "Nature's Remedy (Rank 4)",
        description: "Forages for herbs to mend a wound: heals you for 48 + 32% of your Spell Power. Costs Focus.",
        kind: "heal",
        target: "self",
        ability: "wis",
        flatBase: 48,
        percentOfAbility: 0.64,
        resourceCost: 3,
        apCost: 2,
        schoolId: "martial",
        unlockLevel: 25,
        familyId: "natures-remedy",
        rank: 4,
      },
      {
        id: "pinning-shot",
        name: "Pinning Shot",
        description: "A precise shot to the leg: weapon damage + 20% of your Attack Power, rooting the target in place for 1 turn. Costs Focus.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "ranged",
        damageType: "piercing",
        percentOfAbility: 0.4,
        resourceCost: 2,
        apCost: 2,
        schoolId: "martial",
        applyStatus: { defId: "rooted", turns: 1 },
        unlockLevel: 6,
        familyId: "pinning-shot",
        rank: 1,
      },
      {
        id: "pinning-shot-r2",
        name: "Pinning Shot (Rank 2)",
        description: "A precise shot to the leg: weapon damage + 24% of your Attack Power, rooting the target in place for 1 turn. Costs Focus.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "ranged",
        damageType: "piercing",
        percentOfAbility: 0.48,
        resourceCost: 2,
        apCost: 2,
        schoolId: "martial",
        applyStatus: { defId: "rooted", turns: 1 },
        unlockLevel: 16,
        familyId: "pinning-shot",
        rank: 2,
      },
      {
        id: "pinning-shot-r3",
        name: "Pinning Shot (Rank 3)",
        description: "A precise shot to the leg: weapon damage + 28% of your Attack Power, rooting the target in place for 1 turn. Costs Focus.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "ranged",
        damageType: "piercing",
        percentOfAbility: 0.56,
        resourceCost: 3,
        apCost: 2,
        schoolId: "martial",
        applyStatus: { defId: "rooted", turns: 1 },
        unlockLevel: 23,
        familyId: "pinning-shot",
        rank: 3,
      },
      {
        id: "evasive-maneuvers",
        name: "Evasive Maneuvers",
        description: "A burst of nimble footwork: for 3 turns, evasion increases by 60% of your Dexterity score. Costs Focus.",
        kind: "buff",
        target: "self",
        ability: "dex",
        resourceCost: 2,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "evasive", turns: 3, power: 0.6 },
        unlockLevel: 8,
        familyId: "evasive-maneuvers",
        rank: 1,
      },
      {
        id: "evasive-maneuvers-r2",
        name: "Evasive Maneuvers (Rank 2)",
        description: "A burst of nimble footwork: for 3 turns, evasion increases by 75% of your Dexterity score. Costs Focus.",
        kind: "buff",
        target: "self",
        ability: "dex",
        resourceCost: 2,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "evasive", turns: 3, power: 0.75 },
        unlockLevel: 17,
        familyId: "evasive-maneuvers",
        rank: 2,
      },
      {
        id: "evasive-maneuvers-r3",
        name: "Evasive Maneuvers (Rank 3)",
        description: "A burst of nimble footwork: for 4 turns, evasion increases by 90% of your Dexterity score. Costs Focus.",
        kind: "buff",
        target: "self",
        ability: "dex",
        resourceCost: 2,
        apCost: 1,
        schoolId: "martial",
        applyStatus: { defId: "evasive", turns: 4, power: 0.9 },
        unlockLevel: 24,
        familyId: "evasive-maneuvers",
        rank: 3,
      },
      {
        id: "kill-shot",
        name: "Kill Shot",
        description:
          "A perfectly placed, lethal shot. Weapon damage + 40% of your Attack Power. Requires Evasive. Costs Focus.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "ranged",
        damageType: "piercing",
        percentOfAbility: 0.8,
        resourceCost: 4,
        apCost: 3,
        schoolId: "martial",
        requiresStatusDefId: "evasive",
        unlockLevel: 10,
        familyId: "kill-shot",
        rank: 1,
      },
      {
        id: "kill-shot-r2",
        name: "Kill Shot (Rank 2)",
        description:
          "A perfectly placed, lethal shot. Weapon damage + 50% of your Attack Power. Requires Evasive. Costs Focus.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "ranged",
        damageType: "piercing",
        percentOfAbility: 1.0,
        resourceCost: 4,
        apCost: 3,
        schoolId: "martial",
        requiresStatusDefId: "evasive",
        unlockLevel: 19,
        familyId: "kill-shot",
        rank: 2,
      },
      {
        id: "kill-shot-r3",
        name: "Kill Shot (Rank 3)",
        description:
          "A perfectly placed, lethal shot. Weapon damage + 60% of your Attack Power. Requires Evasive. Costs Focus.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "ranged",
        damageType: "piercing",
        percentOfAbility: 1.2,
        resourceCost: 5,
        apCost: 3,
        schoolId: "martial",
        requiresStatusDefId: "evasive",
        unlockLevel: 26,
        familyId: "kill-shot",
        rank: 3,
      },
      {
        id: "kill-shot-r4",
        name: "Kill Shot (Rank 4)",
        description:
          "A perfectly placed, lethal shot. Weapon damage + 70% of your Attack Power. Requires Evasive. Costs Focus.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "ranged",
        damageType: "piercing",
        percentOfAbility: 1.4,
        resourceCost: 5,
        apCost: 3,
        schoolId: "martial",
        requiresStatusDefId: "evasive",
        unlockLevel: 30,
        familyId: "kill-shot",
        rank: 4,
      },
    ],
    passives: [
      {
        name: "Sharpshooter",
        description: "Increases hit chance and critical chance by 5% while attacking with a ranged weapon.",
      },
    ],
    // Sharpshooter: +5% hit and crit chance with their ranged weapon (see rangedAttackHitBonus's own doc comment).
    rangedAttackHitBonus: 5,
    rangedAttackCritBonus: 5,
    startingEquipmentOptions: [
      {
        id: "bow-and-dagger",
        label: "Shortbow, Dagger & Leather Armor",
        equipment: { rangedWeapon: "huntersShortbow", meleeWeapon: "ritualDagger", armor: "leatherArmor" },
      },
    ],
    startingInventory: ["luckyCharm"],
  },
  rogue: {
    id: "rogue",
    name: "Rogue",
    description: "Quick blades from the shadows. Rogues win by striking first and striking smart.",
    primaryAbility: "dex",
    savingThrowProficiencies: ["dex", "int"],
    evenLevelAbilityGrowth: { dex: 3 },
    // "Attack Power = Dexterity * 2 or Strength * 2 (whichever is higher)" -- same rule as Soldier.
    basicAttackAbilityMode: "highestOfStrDex",
    basicAttackMelee: { name: "Subtle Slash", ability: "str", percentOfAbility: 0.3 },
    basicAttackRanged: { name: "Quick Strike", ability: "dex", percentOfAbility: 0.3 },
    /**
     * Same ranked-ability shape as the Warrior/Soldier/Cleric/Ranger (see
     * those classes' own doc comments): the Rogue's full 5-active kit is
     * online by level 10, then ranks up through 30. Cunning's 30-point cap
     * is bigger than Prayer/Focus but costs are already a similar fraction
     * of it (50-66% per existing lvl2/4 ability), so this kit follows the
     * same "5 actives, 2-5-ish-point-scale-relative costs" shape as
     * Soldier/Cleric/Ranger rather than the Warrior's 6. Vanish -> Assassinate
     * is the Rogue's own stance/gated-finisher pair (mirroring Enrage ->
     * Furious Strike, Riposte Stance -> Counter-Strike, Evasive Maneuvers ->
     * Kill Shot), using a new "veiled" buff id (status.ts). Garrote claims
     * the engine's last unclaimed CC status, "stunned".
     */
    actions: [
      {
        id: "evasive-jab",
        name: "Evasive Jab",
        description:
          "A quick strike through your foe's guard: weapon damage + 20% of your Attack Power, then Readied (1 stack, -50% chance to be hit) until spent. Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.4,
        resourceCost: 20,
        apCost: 3,
        schoolId: "shadow",
        applySelfStatus: { defId: "readied", turns: 99, stacks: 1 },
        unlockLevel: 2,
        familyId: "evasive-jab",
        rank: 1,
      },
      {
        id: "evasive-jab-r2",
        name: "Evasive Jab (Rank 2)",
        description:
          "A quick strike through your foe's guard: weapon damage + 24% of your Attack Power, then Readied (1 stack, -50% chance to be hit) until spent. Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.48,
        resourceCost: 20,
        apCost: 3,
        schoolId: "shadow",
        applySelfStatus: { defId: "readied", turns: 99, stacks: 1 },
        unlockLevel: 11,
        familyId: "evasive-jab",
        rank: 2,
      },
      {
        id: "evasive-jab-r3",
        name: "Evasive Jab (Rank 3)",
        description:
          "A quick strike through your foe's guard: weapon damage + 28% of your Attack Power, then Readied (2 stacks, -50% chance to be hit each) until spent. Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.56,
        resourceCost: 22,
        apCost: 3,
        schoolId: "shadow",
        applySelfStatus: { defId: "readied", turns: 99, stacks: 2 },
        unlockLevel: 18,
        familyId: "evasive-jab",
        rank: 3,
      },
      {
        id: "evasive-jab-r4",
        name: "Evasive Jab (Rank 4)",
        description:
          "A quick strike through your foe's guard: weapon damage + 32% of your Attack Power, then Readied (2 stacks, -50% chance to be hit each) until spent. Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.64,
        resourceCost: 22,
        apCost: 3,
        schoolId: "shadow",
        applySelfStatus: { defId: "readied", turns: 99, stacks: 2 },
        unlockLevel: 25,
        familyId: "evasive-jab",
        rank: 4,
      },
      {
        id: "poisoned-throw",
        name: "Poisoned Throw",
        description:
          "A blade dipped in poison: weapon damage + 15% of your Attack Power, poisoning the target for 3 turns (10% Attack Power per turn). Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.3,
        resourceCost: 15,
        apCost: 2,
        schoolId: "shadow",
        applyStatus: { defId: "poisoned", turns: 3, power: 0.2 },
        unlockLevel: 4,
        familyId: "poisoned-throw",
        rank: 1,
      },
      {
        id: "poisoned-throw-r2",
        name: "Poisoned Throw (Rank 2)",
        description:
          "A blade dipped in poison: weapon damage + 18% of your Attack Power, poisoning the target for 3 turns (12% Attack Power per turn). Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.36,
        resourceCost: 16,
        apCost: 2,
        schoolId: "shadow",
        applyStatus: { defId: "poisoned", turns: 3, power: 0.24 },
        unlockLevel: 12,
        familyId: "poisoned-throw",
        rank: 2,
      },
      {
        id: "poisoned-throw-r3",
        name: "Poisoned Throw (Rank 3)",
        description:
          "A blade dipped in poison: weapon damage + 21% of your Attack Power, poisoning the target for 3 turns (14% Attack Power per turn). Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.42,
        resourceCost: 17,
        apCost: 2,
        schoolId: "shadow",
        applyStatus: { defId: "poisoned", turns: 3, power: 0.28 },
        unlockLevel: 19,
        familyId: "poisoned-throw",
        rank: 3,
      },
      {
        id: "poisoned-throw-r4",
        name: "Poisoned Throw (Rank 4)",
        description:
          "A blade dipped in poison: weapon damage + 24% of your Attack Power, poisoning the target for 3 turns (16% Attack Power per turn). Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.48,
        resourceCost: 18,
        apCost: 2,
        schoolId: "shadow",
        applyStatus: { defId: "poisoned", turns: 3, power: 0.32 },
        unlockLevel: 26,
        familyId: "poisoned-throw",
        rank: 4,
      },
      {
        id: "garrote",
        name: "Garrote",
        description: "A choking strike from the shadows: weapon damage + 15% of your Attack Power, stunning the target for 1 turn. Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.3,
        resourceCost: 18,
        apCost: 2,
        schoolId: "shadow",
        applyStatus: { defId: "stunned", turns: 1 },
        unlockLevel: 6,
        familyId: "garrote",
        rank: 1,
      },
      {
        id: "garrote-r2",
        name: "Garrote (Rank 2)",
        description: "A choking strike from the shadows: weapon damage + 18% of your Attack Power, stunning the target for 1 turn. Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.36,
        resourceCost: 19,
        apCost: 2,
        schoolId: "shadow",
        applyStatus: { defId: "stunned", turns: 1 },
        unlockLevel: 17,
        familyId: "garrote",
        rank: 2,
      },
      {
        id: "garrote-r3",
        name: "Garrote (Rank 3)",
        description: "A choking strike from the shadows: weapon damage + 21% of your Attack Power, stunning the target for 1 turn. Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.42,
        resourceCost: 20,
        apCost: 2,
        schoolId: "shadow",
        applyStatus: { defId: "stunned", turns: 1 },
        unlockLevel: 24,
        familyId: "garrote",
        rank: 3,
      },
      {
        id: "vanish",
        name: "Vanish",
        description: "Melts into the shadows: for 3 turns, evasion increases by 60% of your Dexterity score. Costs Cunning.",
        kind: "buff",
        target: "self",
        ability: "dex",
        resourceCost: 10,
        apCost: 1,
        schoolId: "shadow",
        applyStatus: { defId: "veiled", turns: 3, power: 0.6 },
        unlockLevel: 8,
        familyId: "vanish",
        rank: 1,
      },
      {
        id: "vanish-r2",
        name: "Vanish (Rank 2)",
        description: "Melts into the shadows: for 3 turns, evasion increases by 75% of your Dexterity score. Costs Cunning.",
        kind: "buff",
        target: "self",
        ability: "dex",
        resourceCost: 10,
        apCost: 1,
        schoolId: "shadow",
        applyStatus: { defId: "veiled", turns: 3, power: 0.75 },
        unlockLevel: 16,
        familyId: "vanish",
        rank: 2,
      },
      {
        id: "vanish-r3",
        name: "Vanish (Rank 3)",
        description: "Melts into the shadows: for 4 turns, evasion increases by 90% of your Dexterity score. Costs Cunning.",
        kind: "buff",
        target: "self",
        ability: "dex",
        resourceCost: 12,
        apCost: 1,
        schoolId: "shadow",
        applyStatus: { defId: "veiled", turns: 4, power: 0.9 },
        unlockLevel: 23,
        familyId: "vanish",
        rank: 3,
      },
      {
        id: "assassinate",
        name: "Assassinate",
        description: "A single, lethal strike from hiding. Weapon damage + 40% of your Attack Power. Requires Veiled. Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 0.8,
        resourceCost: 25,
        apCost: 3,
        schoolId: "shadow",
        requiresStatusDefId: "veiled",
        unlockLevel: 10,
        familyId: "assassinate",
        rank: 1,
      },
      {
        id: "assassinate-r2",
        name: "Assassinate (Rank 2)",
        description: "A single, lethal strike from hiding. Weapon damage + 50% of your Attack Power. Requires Veiled. Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 1.0,
        resourceCost: 26,
        apCost: 3,
        schoolId: "shadow",
        requiresStatusDefId: "veiled",
        unlockLevel: 20,
        familyId: "assassinate",
        rank: 2,
      },
      {
        id: "assassinate-r3",
        name: "Assassinate (Rank 3)",
        description: "A single, lethal strike from hiding. Weapon damage + 60% of your Attack Power. Requires Veiled. Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 1.2,
        resourceCost: 27,
        apCost: 3,
        schoolId: "shadow",
        requiresStatusDefId: "veiled",
        unlockLevel: 27,
        familyId: "assassinate",
        rank: 3,
      },
      {
        id: "assassinate-r4",
        name: "Assassinate (Rank 4)",
        description: "A single, lethal strike from hiding. Weapon damage + 70% of your Attack Power. Requires Veiled. Costs Cunning.",
        kind: "attack",
        target: "enemy",
        ability: "dex",
        weaponDamageSource: "melee",
        damageType: "piercing",
        percentOfAbility: 1.4,
        resourceCost: 28,
        apCost: 3,
        schoolId: "shadow",
        requiresStatusDefId: "veiled",
        unlockLevel: 30,
        familyId: "assassinate",
        rank: 4,
      },
    ],
    // The Class Style Sheet itself just says "Placeholder" for Rogue's passive -- left unimplemented
    // rather than invented, so `passives` stays empty (no card shows on the Character screen).
    passives: [],
    startingEquipmentOptions: [
      { id: "shortbow", label: "Shortbow & Leather Armor", equipment: { rangedWeapon: "huntersShortbow", armor: "leatherArmor" } },
      { id: "shortsword", label: "Shortsword & Leather Armor", equipment: { meleeWeapon: "shortsword", armor: "leatherArmor" } },
    ],
    startingInventory: ["ringOfWarding"],
  },
  druid: {
    id: "druid",
    name: "Druid",
    description: "Wardens of root and bloom, drawing on nature's own magic in battle.",
    primaryAbility: "wis",
    savingThrowProficiencies: ["int", "wis"],
    evenLevelAbilityGrowth: { wis: 2, vit: 1, dex: 1 },
    basicAttackMelee: { name: "Nature's Strike", ability: "str", percentOfAbility: 0.3 },
    basicAttackRanged: { name: "Nature's Blast", ability: "wis", percentOfAbility: 0.3 },
    /**
     * Same ranked-ability shape as the other five classes (see their own
     * doc comments), but a bigger kit (6 actives, like the Warrior) since
     * Wylde is a mana-like pool (full at combat start, scales with Wisdom
     * and level -- see stats.ts) rather than the tiny fixed pools the last
     * four classes built around. Barkskin -> Savage Growth is the Druid's
     * own stance/gated-finisher pair (mirroring Enrage -> Furious Strike,
     * etc.), using a new "barkskin" buff id (status.ts). Entangling Roots
     * reuses "rooted" (already claimed by the Ranger's Pinning Shot -- CC
     * flavors aren't exclusive the way a buff's `requiresStatusDefId` gate
     * is, so two classes applying the same CC is fine). Bloom finally
     * claims the engine's own "bloom" HoT status, present since the
     * AP-economy rebuild but unused until now -- fitting, since it was
     * clearly meant for exactly this class.
     */
    actions: [
      {
        id: "wylde-healing",
        name: "Wylde Healing",
        description: "Summons the will of the Wylde to heal yourself or an ally for 40 + 20% of your Spell Power. Costs Wylde.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 40,
        percentOfAbility: 0.4,
        resourceCost: 30,
        apCost: 2,
        schoolId: "nature",
        unlockLevel: 2,
        familyId: "wylde-healing",
        rank: 1,
      },
      {
        id: "wylde-healing-r2",
        name: "Wylde Healing (Rank 2)",
        description: "Summons the will of the Wylde to heal yourself or an ally for 48 + 24% of your Spell Power. Costs Wylde.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 48,
        percentOfAbility: 0.48,
        resourceCost: 32,
        apCost: 2,
        schoolId: "nature",
        unlockLevel: 11,
        familyId: "wylde-healing",
        rank: 2,
      },
      {
        id: "wylde-healing-r3",
        name: "Wylde Healing (Rank 3)",
        description: "Summons the will of the Wylde to heal yourself or an ally for 56 + 28% of your Spell Power. Costs Wylde.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 56,
        percentOfAbility: 0.56,
        resourceCost: 34,
        apCost: 2,
        schoolId: "nature",
        unlockLevel: 18,
        familyId: "wylde-healing",
        rank: 3,
      },
      {
        id: "wylde-healing-r4",
        name: "Wylde Healing (Rank 4)",
        description: "Summons the will of the Wylde to heal yourself or an ally for 64 + 32% of your Spell Power. Costs Wylde.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 64,
        percentOfAbility: 0.64,
        resourceCost: 36,
        apCost: 2,
        schoolId: "nature",
        unlockLevel: 25,
        familyId: "wylde-healing",
        rank: 4,
      },
      {
        id: "wylde-wrath",
        name: "Wylde Wrath",
        description: "A massive vine whips in a wide arc, striking an entire row of enemies for 60 + 25% of your Spell Power. Costs Wylde.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "wis",
        damageType: "piercing",
        flatBase: 60,
        percentOfAbility: 0.5,
        resourceCost: 70,
        apCost: 3,
        schoolId: "nature",
        unlockLevel: 4,
        familyId: "wylde-wrath",
        rank: 1,
      },
      {
        id: "wylde-wrath-r2",
        name: "Wylde Wrath (Rank 2)",
        description: "A massive vine whips in a wide arc, striking an entire row of enemies for 70 + 30% of your Spell Power. Costs Wylde.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "wis",
        damageType: "piercing",
        flatBase: 70,
        percentOfAbility: 0.6,
        resourceCost: 75,
        apCost: 3,
        schoolId: "nature",
        unlockLevel: 12,
        familyId: "wylde-wrath",
        rank: 2,
      },
      {
        id: "wylde-wrath-r3",
        name: "Wylde Wrath (Rank 3)",
        description: "A massive vine whips in a wide arc, striking an entire row of enemies for 80 + 35% of your Spell Power. Costs Wylde.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "wis",
        damageType: "piercing",
        flatBase: 80,
        percentOfAbility: 0.7,
        resourceCost: 80,
        apCost: 3,
        schoolId: "nature",
        unlockLevel: 19,
        familyId: "wylde-wrath",
        rank: 3,
      },
      {
        id: "wylde-wrath-r4",
        name: "Wylde Wrath (Rank 4)",
        description: "A massive vine whips in a wide arc, striking an entire row of enemies for 90 + 40% of your Spell Power. Costs Wylde.",
        kind: "attack",
        target: "enemy",
        targetShape: "line",
        ability: "wis",
        damageType: "piercing",
        flatBase: 90,
        percentOfAbility: 0.8,
        resourceCost: 85,
        apCost: 3,
        schoolId: "nature",
        unlockLevel: 26,
        familyId: "wylde-wrath",
        rank: 4,
      },
      {
        id: "entangling-roots",
        name: "Entangling Roots",
        description: "Thorny vines burst from the ground: deals 30 + 15% of your Spell Power and roots the target in place for 1 turn. Costs Wylde.",
        kind: "attack",
        target: "enemy",
        ability: "wis",
        damageType: "piercing",
        flatBase: 30,
        percentOfAbility: 0.3,
        resourceCost: 40,
        apCost: 2,
        schoolId: "nature",
        applyStatus: { defId: "rooted", turns: 1 },
        unlockLevel: 6,
        familyId: "entangling-roots",
        rank: 1,
      },
      {
        id: "entangling-roots-r2",
        name: "Entangling Roots (Rank 2)",
        description: "Thorny vines burst from the ground: deals 36 + 18% of your Spell Power and roots the target in place for 1 turn. Costs Wylde.",
        kind: "attack",
        target: "enemy",
        ability: "wis",
        damageType: "piercing",
        flatBase: 36,
        percentOfAbility: 0.36,
        resourceCost: 42,
        apCost: 2,
        schoolId: "nature",
        applyStatus: { defId: "rooted", turns: 1 },
        unlockLevel: 17,
        familyId: "entangling-roots",
        rank: 2,
      },
      {
        id: "entangling-roots-r3",
        name: "Entangling Roots (Rank 3)",
        description: "Thorny vines burst from the ground: deals 42 + 21% of your Spell Power and roots the target in place for 1 turn. Costs Wylde.",
        kind: "attack",
        target: "enemy",
        ability: "wis",
        damageType: "piercing",
        flatBase: 42,
        percentOfAbility: 0.42,
        resourceCost: 44,
        apCost: 2,
        schoolId: "nature",
        applyStatus: { defId: "rooted", turns: 1 },
        unlockLevel: 24,
        familyId: "entangling-roots",
        rank: 3,
      },
      {
        id: "barkskin",
        name: "Barkskin",
        description: "Your skin hardens like bark: for 3 turns, evasion increases by 60% of your Wisdom score. Costs Wylde.",
        kind: "buff",
        target: "self",
        ability: "wis",
        resourceCost: 25,
        apCost: 1,
        schoolId: "nature",
        applyStatus: { defId: "barkskin", turns: 3, power: 0.6 },
        unlockLevel: 8,
        familyId: "barkskin",
        rank: 1,
      },
      {
        id: "barkskin-r2",
        name: "Barkskin (Rank 2)",
        description: "Your skin hardens like bark: for 3 turns, evasion increases by 75% of your Wisdom score. Costs Wylde.",
        kind: "buff",
        target: "self",
        ability: "wis",
        resourceCost: 25,
        apCost: 1,
        schoolId: "nature",
        applyStatus: { defId: "barkskin", turns: 3, power: 0.75 },
        unlockLevel: 16,
        familyId: "barkskin",
        rank: 2,
      },
      {
        id: "barkskin-r3",
        name: "Barkskin (Rank 3)",
        description: "Your skin hardens like bark: for 4 turns, evasion increases by 90% of your Wisdom score. Costs Wylde.",
        kind: "buff",
        target: "self",
        ability: "wis",
        resourceCost: 28,
        apCost: 1,
        schoolId: "nature",
        applyStatus: { defId: "barkskin", turns: 4, power: 0.9 },
        unlockLevel: 23,
        familyId: "barkskin",
        rank: 3,
      },
      {
        id: "bloom",
        name: "Bloom",
        description:
          "Wraps an ally in verdant growth: heals for 20, then another 15% of your Spell Power at the start of each of their turns for 3 turns. Costs Wylde.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 20,
        resourceCost: 35,
        apCost: 2,
        schoolId: "nature",
        applyStatus: { defId: "bloom", turns: 3, power: 0.3 },
        unlockLevel: 9,
        familyId: "bloom",
        rank: 1,
      },
      {
        id: "bloom-r2",
        name: "Bloom (Rank 2)",
        description:
          "Wraps an ally in verdant growth: heals for 26, then another 18% of your Spell Power at the start of each of their turns for 3 turns. Costs Wylde.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 26,
        resourceCost: 37,
        apCost: 2,
        schoolId: "nature",
        applyStatus: { defId: "bloom", turns: 3, power: 0.36 },
        unlockLevel: 20,
        familyId: "bloom",
        rank: 2,
      },
      {
        id: "bloom-r3",
        name: "Bloom (Rank 3)",
        description:
          "Wraps an ally in verdant growth: heals for 32, then another 21% of your Spell Power at the start of each of their turns for 4 turns. Costs Wylde.",
        kind: "heal",
        target: "ally",
        ability: "wis",
        flatBase: 32,
        resourceCost: 39,
        apCost: 2,
        schoolId: "nature",
        applyStatus: { defId: "bloom", turns: 4, power: 0.42 },
        unlockLevel: 27,
        familyId: "bloom",
        rank: 3,
      },
      {
        id: "savage-growth",
        name: "Savage Growth",
        description:
          "A violent surge of nature's fury. Deals 60 + 25% of your Spell Power. Requires Barkskin. Costs Wylde.",
        kind: "attack",
        target: "enemy",
        ability: "wis",
        damageType: "piercing",
        flatBase: 60,
        percentOfAbility: 0.5,
        resourceCost: 80,
        apCost: 3,
        schoolId: "nature",
        requiresStatusDefId: "barkskin",
        unlockLevel: 10,
        familyId: "savage-growth",
        rank: 1,
      },
      {
        id: "savage-growth-r2",
        name: "Savage Growth (Rank 2)",
        description:
          "A violent surge of nature's fury. Deals 70 + 30% of your Spell Power. Requires Barkskin. Costs Wylde.",
        kind: "attack",
        target: "enemy",
        ability: "wis",
        damageType: "piercing",
        flatBase: 70,
        percentOfAbility: 0.6,
        resourceCost: 85,
        apCost: 3,
        schoolId: "nature",
        requiresStatusDefId: "barkskin",
        unlockLevel: 19,
        familyId: "savage-growth",
        rank: 2,
      },
      {
        id: "savage-growth-r3",
        name: "Savage Growth (Rank 3)",
        description:
          "A violent surge of nature's fury. Deals 80 + 35% of your Spell Power. Requires Barkskin. Costs Wylde.",
        kind: "attack",
        target: "enemy",
        ability: "wis",
        damageType: "piercing",
        flatBase: 80,
        percentOfAbility: 0.7,
        resourceCost: 90,
        apCost: 3,
        schoolId: "nature",
        requiresStatusDefId: "barkskin",
        unlockLevel: 26,
        familyId: "savage-growth",
        rank: 3,
      },
      {
        id: "savage-growth-r4",
        name: "Savage Growth (Rank 4)",
        description:
          "A violent surge of nature's fury. Deals 90 + 40% of your Spell Power. Requires Barkskin. Costs Wylde.",
        kind: "attack",
        target: "enemy",
        ability: "wis",
        damageType: "piercing",
        flatBase: 90,
        percentOfAbility: 0.8,
        resourceCost: 95,
        apCost: 3,
        schoolId: "nature",
        requiresStatusDefId: "barkskin",
        unlockLevel: 30,
        familyId: "savage-growth",
        rank: 4,
      },
    ],
    passives: [
      { name: "Spellcasting", description: "Your spells' damage and healing scale off your Spell Power." },
    ],
    startingEquipmentOptions: [
      {
        id: "mace",
        label: "Ashen Mace, Nature's Blast & Leather Armor",
        equipment: { meleeWeapon: "ashenMace", rangedWeapon: "naturesBlast", armor: "leatherArmor" },
      },
      { id: "shortbow", label: "Shortbow & Leather Armor", equipment: { rangedWeapon: "huntersShortbow", armor: "leatherArmor" } },
    ],
    startingInventory: ["ringOfWarding"],
  },
  wizard: {
    id: "wizard",
    name: "Wizard",
    description: "Scholars of the arcane, channeling raw magic through years of study.",
    primaryAbility: "int",
    savingThrowProficiencies: ["int", "wis"],
    evenLevelAbilityGrowth: { int: 3 },
    basicAttackMelee: { name: "Arcane Smash", ability: "str", percentOfAbility: 0.3 },
    basicAttackRanged: { name: "Arcane Bolt", ability: "int", percentOfAbility: 0.4 },
    actions: [
      {
        id: "elemental-shard",
        name: "Elemental Shard",
        description:
          "Invokes the Arcane, creating a shard of elemental power -- fire, ice, or force at random -- for 35 + 20% of your Spell Power. Costs Arcana.",
        kind: "attack",
        target: "enemy",
        ability: "int",
        randomDamageTypes: ["fire", "cold", "force"],
        flatBase: 35,
        percentOfAbility: 0.4,
        resourceCost: 50,
        apCost: 2,
        schoolId: "arcane",
        unlockLevel: 2,
      },
      {
        id: "arcane-barrier",
        name: "Arcane Barrier",
        description: "Conjures a protective shield: evasion increases by 50% of your Spell Power for 3 turns. Costs Arcana.",
        kind: "buff",
        target: "self",
        ability: "int",
        resourceCost: 30,
        apCost: 2,
        schoolId: "arcane",
        applyStatus: { defId: "fortified", turns: 3, power: 1.0 },
        unlockLevel: 4,
      },
    ],
    passives: [
      { name: "Spellcasting", description: "Your spells' damage and healing scale off your Spell Power." },
    ],
    startingEquipmentOptions: [
      {
        id: "staff",
        label: "Oaken Staff, Arcane Bolt & Traveler's Robe",
        equipment: { meleeWeapon: "oakenStaff", rangedWeapon: "arcaneBolt", armor: "travelersRobe" },
      },
      {
        id: "dagger",
        label: "Ritual Dagger, Arcane Bolt & Traveler's Robe",
        equipment: { meleeWeapon: "ritualDagger", rangedWeapon: "arcaneBolt", armor: "travelersRobe" },
      },
    ],
    startingInventory: ["luckyCharm"],
  },
};

export function getClass(id: string): CharacterClass {
  const cls = CLASSES[id];
  if (!cls) throw new Error(`Unknown class: "${id}"`);
  return cls;
}

/**
 * The ability governing this class's magical attacks (its basic ranged
 * attack, or any damaging spell), or undefined if it has none -- Cleric and
 * Druid (Wisdom) and Wizard (Intellect) today. Used to decide whether the
 * Character screen's Magical Offense section applies, and which score
 * powers it (Character Stats Style Sheet's Spell Power/Magical Critical
 * Chance/Magical Critical Damage).
 */
export function magicalAttackAbility(cls: CharacterClass): AbilityKey | undefined {
  const candidates: AbilityKey[] = [
    cls.basicAttackMelee.ability,
    cls.basicAttackRanged.ability,
    ...cls.actions.filter((a) => a.kind === "attack").map((a) => a.ability),
  ];
  return candidates.find(isMagicalAbility);
}
